# Generated by Django 5.2.17 on 2026-09-14 15:34

import django.db.models.deletion
from django.db import migrations, models


def backfill_memberships(apps, schema_editor):
    Run = apps.get_model("mailings", "ImportRun")
    Record = apps.get_model("mailings", "MailingRecord")
    Entry = apps.get_model("mailings", "ImportEntry")
    alias = schema_editor.connection.alias
    Run.objects.using(alias).filter(status="completed").update(status="imported")
    # v0.1 had no ownership token: an abandoned claim has an unknown outcome.
    Record.objects.using(alias).filter(status="processing").update(status="uncertain")
    batch = []
    for pk, owner in Record.objects.using(alias).values_list("pk", "import_run_id").iterator(chunk_size=1000):
        batch.append(Entry(import_run_id=owner, record_id=pk))
        if len(batch) == 1000:
            Entry.objects.using(alias).bulk_create(batch)
            batch = []
    if batch:
        Entry.objects.using(alias).bulk_create(batch)


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importrun",
            name="delivery_failed_count",
        ),
        migrations.RemoveField(
            model_name="importrun",
            name="sent_count",
        ),
        migrations.AddField(
            model_name="mailingrecord",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailingrecord",
            name="claim_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="mailingrecord",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("imported", "Import finished"),
                    ("failed", "Failed"),
                    ("interrupted", "Interrupted"),
                ],
                default="running",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="mailingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("uncertain", "Outcome unknown"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ImportEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="mailings.importrun"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="mailings.mailingrecord"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("import_run", "record"), name="unique_import_record")],
            },
        ),
        migrations.RunPython(backfill_memberships, migrations.RunPython.noop),
    ]
