# Generated by Django 5.2.17 on 2026-09-14 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0002_resume_delivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mailingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("pending", "processing", "sent", "failed", "uncertain"))),
                name="mail_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sent_at__isnull", False), ("status", "sent")),
                    models.Q(models.Q(("status", "sent"), _negated=True), ("sent_at__isnull", True)),
                    _connector="OR",
                ),
                name="mail_sent_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("claim_token__isnull", False), ("claimed_at__isnull", False), ("status", "processing")),
                    models.Q(
                        models.Q(("status", "processing"), _negated=True),
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="mail_processing_claim",
            ),
        ),
    ]
